services:
  web:
    image: php:8.1-apache
    ports:
      - "8180:80"
    restart: unless-stopped
    volumes:
      - ../src/:/var/www/html/
    command:
      /bin/bash -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && apache2-foreground"
    
